import { Inject, Injectable, Logger } from '@nestjs/common';
import { AxiosError } from 'axios';
import { and, asc, count, eq } from 'drizzle-orm';
import { AuthService } from '../auth/auth.service.js';
import { DB } from '../db/db.constants.js';
import type { Database } from '../db/db.module.js';
import { type PendingAction, pendingActions } from '../db/schema.js';
import { OAuthAppsService } from '../oauth-apps/oauth-apps.service.js';
import { SoundcloudService } from '../soundcloud/soundcloud.service.js';

export type ActionType =
  | 'like'
  | 'unlike'
  | 'repost'
  | 'unrepost'
  | 'comment'
  | 'playlist_create'
  | 'playlist_update'
  | 'playlist_delete'
  | 'like_playlist'
  | 'unlike_playlist'
  | 'repost_playlist'
  | 'unrepost_playlist';

const MAX_RETRIES = 5;
const SYNC_INTERVAL_MS = 60 * 1000;

@Injectable()
export class PendingActionsService {
  private readonly logger = new Logger(PendingActionsService.name);
  private syncTimer: ReturnType<typeof setInterval> | null = null;

  constructor(
    @Inject(DB) private readonly db: Database,
    private readonly sc: SoundcloudService,
    private readonly authService: AuthService,
    private readonly oauthAppsService: OAuthAppsService,
  ) {}

  onModuleInit() {
    this.syncTimer = setInterval(() => {
      this.syncAll().catch((err) => {
        this.logger.error(`Sync failed: ${err.message}`);
      });
    }, SYNC_INTERVAL_MS);
    this.logger.log(`Pending actions sync started (interval: ${SYNC_INTERVAL_MS / 1000}s)`);
  }

  onModuleDestroy() {
    if (this.syncTimer) clearInterval(this.syncTimer);
  }

  isBanError(error: unknown): boolean {
    if (error instanceof AxiosError && error.response) {
      const { status, data } = error.response;
      if (status !== 403) return false;
      const body = typeof data === 'string' ? data : JSON.stringify(data);
      const lower = body.toLowerCase();
      return (
        lower.includes('request blocked') ||
        lower.includes('the request could not be satisfied') ||
        lower.includes('generated by cloudfront')
      );
    }
    return false;
  }

  async enqueue(
    sessionId: string,
    actionType: ActionType,
    targetUrn: string,
    payload?: Record<string, unknown> | null,
  ): Promise<PendingAction> {
    const existing = await this.db.query.pendingActions.findFirst({
      where: and(
        eq(pendingActions.sessionId, sessionId),
        eq(pendingActions.actionType, actionType),
        eq(pendingActions.targetUrn, targetUrn),
        eq(pendingActions.status, 'pending'),
      ),
    });

    if (existing) {
      const [updated] = await this.db
        .update(pendingActions)
        .set({
          payload: payload ?? existing.payload,
          retryCount: 0,
          error: null,
        })
        .where(eq(pendingActions.id, existing.id))
        .returning();
      return updated;
    }

    const [saved] = await this.db
      .insert(pendingActions)
      .values({
        sessionId,
        actionType,
        targetUrn,
        payload: payload ?? null,
        status: 'pending',
      })
      .returning();
    this.logger.log(`Enqueued: ${actionType} ${targetUrn} for session ${sessionId.slice(0, 8)}...`);
    return saved;
  }

  async getForSession(sessionId: string): Promise<PendingAction[]> {
    return this.db
      .select()
      .from(pendingActions)
      .where(and(eq(pendingActions.sessionId, sessionId), eq(pendingActions.status, 'pending')))
      .orderBy(asc(pendingActions.createdAt));
  }

  async getStats(sessionId: string): Promise<{ pending: number; failed: number }> {
    const countWhere = (status: 'pending' | 'failed') =>
      this.db
        .select({ n: count() })
        .from(pendingActions)
        .where(and(eq(pendingActions.sessionId, sessionId), eq(pendingActions.status, status)))
        .then((r) => r[0]?.n ?? 0);
    const [pending, failed] = await Promise.all([countWhere('pending'), countWhere('failed')]);
    return { pending, failed };
  }

  async syncAll(): Promise<{ synced: number; failed: number }> {
    if (!(await this.oauthAppsService.hasActiveApp())) {
      return { synced: 0, failed: 0 };
    }

    const actions = await this.db
      .select()
      .from(pendingActions)
      .where(eq(pendingActions.status, 'pending'))
      .orderBy(asc(pendingActions.createdAt))
      .limit(50);

    if (actions.length === 0) return { synced: 0, failed: 0 };

    this.logger.log(`Syncing ${actions.length} pending actions...`);

    let synced = 0;
    let failed = 0;

    for (const action of actions) {
      const update: Partial<PendingAction> = {};
      try {
        await this.executeAction(action);
        update.status = 'done';
        synced++;
      } catch (err: any) {
        if (this.isBanError(err)) {
          this.logger.warn(
            `Still banned, skipping sync for ${action.actionType} ${action.targetUrn}`,
          );
          break;
        }
        update.retryCount = action.retryCount + 1;
        update.error = err.message?.slice(0, 500) ?? 'Unknown error';
        if ((update.retryCount ?? 0) >= MAX_RETRIES) {
          update.status = 'failed';
          failed++;
          this.logger.warn(`Action failed permanently: ${action.actionType} ${action.targetUrn}`);
        }
      }
      await this.db
        .update(pendingActions)
        .set(update)
        .where(eq(pendingActions.id, action.id));
    }

    if (synced > 0) {
      this.logger.log(`Sync complete: ${synced} synced, ${failed} failed`);
    }
    return { synced, failed };
  }

  async syncForSession(sessionId: string): Promise<{ synced: number; failed: number }> {
    const actions = await this.db
      .select()
      .from(pendingActions)
      .where(and(eq(pendingActions.sessionId, sessionId), eq(pendingActions.status, 'pending')))
      .orderBy(asc(pendingActions.createdAt));

    let synced = 0;
    let failed = 0;

    for (const action of actions) {
      const update: Partial<PendingAction> = {};
      try {
        await this.executeAction(action);
        update.status = 'done';
        synced++;
      } catch (err: any) {
        if (this.isBanError(err)) break;
        update.retryCount = action.retryCount + 1;
        update.error = err.message?.slice(0, 500) ?? 'Unknown error';
        if ((update.retryCount ?? 0) >= MAX_RETRIES) {
          update.status = 'failed';
          failed++;
        }
      }
      await this.db
        .update(pendingActions)
        .set(update)
        .where(eq(pendingActions.id, action.id));
    }

    return { synced, failed };
  }

  private async executeAction(action: PendingAction): Promise<void> {
    const token = await this.authService.getValidAccessToken(action.sessionId);

    switch (action.actionType as ActionType) {
      case 'like':
        await this.sc.apiPost(`/likes/tracks/${action.targetUrn}`, token);
        break;
      case 'unlike':
        await this.sc.apiDelete(`/likes/tracks/${action.targetUrn}`, token);
        break;
      case 'repost':
        await this.sc.apiPost(`/reposts/tracks/${action.targetUrn}`, token);
        break;
      case 'unrepost':
        await this.sc.apiDelete(`/reposts/tracks/${action.targetUrn}`, token);
        break;
      case 'comment':
        await this.sc.apiPost(`/tracks/${action.targetUrn}/comments`, token, action.payload);
        break;
      case 'like_playlist':
        await this.sc.apiPost(`/likes/playlists/${action.targetUrn}`, token);
        break;
      case 'unlike_playlist':
        await this.sc.apiDelete(`/likes/playlists/${action.targetUrn}`, token);
        break;
      case 'repost_playlist':
        await this.sc.apiPost(`/reposts/playlists/${action.targetUrn}`, token);
        break;
      case 'unrepost_playlist':
        await this.sc.apiDelete(`/reposts/playlists/${action.targetUrn}`, token);
        break;
      case 'playlist_create':
        await this.sc.apiPost('/playlists', token, action.payload);
        break;
      case 'playlist_update':
        await this.sc.apiPut(`/playlists/${action.targetUrn}`, token, action.payload);
        break;
      case 'playlist_delete':
        await this.sc.apiDelete(`/playlists/${action.targetUrn}`, token);
        break;
      default:
        this.logger.warn(`Unknown action type: ${action.actionType}`);
    }
  }
}
