use std::sync::Arc;

use chrono::NaiveDateTime;
use serde::Serialize;
use serde_json::Value;
use sqlx::types::Uuid;
use sqlx::PgPool;
use tracing::warn;

use crate::error::{AppError, AppResult};
use crate::modules::auth::AuthService;
use crate::modules::oauth_apps::OAuthAppsService;
use crate::sc::ScClient;

const MAX_RETRIES: i32 = 5;

#[derive(Debug, Clone, Serialize, sqlx::FromRow)]
pub struct PendingAction {
    pub id: Uuid,
    pub session_id: String,
    pub action_type: String,
    pub target_urn: String,
    pub payload: Option<Value>,
    pub status: String,
    pub error: Option<String>,
    pub retry_count: i32,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
}

#[derive(Debug, Serialize)]
pub struct SyncStats {
    pub synced: usize,
    pub failed: usize,
}

#[derive(Debug, Serialize)]
pub struct PendingStats {
    pub pending: i64,
    pub failed: i64,
}

pub struct PendingActionsService {
    pg: PgPool,
    sc: ScClient,
    auth: Arc<AuthService>,
    oauth_apps: Arc<OAuthAppsService>,
}

impl PendingActionsService {
    pub fn new(
        pg: PgPool,
        sc: ScClient,
        auth: Arc<AuthService>,
        oauth_apps: Arc<OAuthAppsService>,
    ) -> Arc<Self> {
        Arc::new(Self {
            pg,
            sc,
            auth,
            oauth_apps,
        })
    }

    /// 403 + body содержит маркеры CloudFront/Cloudflare ban — действие в очередь.
    pub fn is_ban_error(err: &AppError) -> bool {
        let AppError::ScApi { status, body } = err else {
            return false;
        };
        if *status != 403 {
            return false;
        }
        let body_str = match body {
            Value::String(s) => s.clone(),
            other => other.to_string(),
        };
        let lower = body_str.to_lowercase();
        lower.contains("request blocked")
            || lower.contains("the request could not be satisfied")
            || lower.contains("generated by cloudfront")
    }

    pub async fn enqueue(
        &self,
        session_id: &str,
        action_type: &str,
        target_urn: &str,
        payload: Option<&Value>,
    ) -> AppResult<PendingAction> {
        let existing: Option<PendingAction> = sqlx::query_as(
            "SELECT * FROM pending_actions \
             WHERE session_id = $1 AND action_type = $2 AND target_urn = $3 AND status = 'pending' \
             LIMIT 1",
        )
        .bind(session_id)
        .bind(action_type)
        .bind(target_urn)
        .fetch_optional(&self.pg)
        .await?;

        if let Some(row) = existing {
            let updated: PendingAction = sqlx::query_as(
                "UPDATE pending_actions \
                 SET payload = COALESCE($1, payload), retry_count = 0, error = NULL, updated_at = now() \
                 WHERE id = $2 RETURNING *",
            )
            .bind(payload)
            .bind(row.id)
            .fetch_one(&self.pg)
            .await?;
            return Ok(updated);
        }

        let id = Uuid::new_v4();
        let saved: PendingAction = sqlx::query_as(
            "INSERT INTO pending_actions (id, session_id, action_type, target_urn, payload, status) \
             VALUES ($1, $2, $3, $4, $5, 'pending') RETURNING *",
        )
        .bind(id)
        .bind(session_id)
        .bind(action_type)
        .bind(target_urn)
        .bind(payload)
        .fetch_one(&self.pg)
        .await?;
        Ok(saved)
    }

    pub async fn get_for_session(&self, session_id: &str) -> AppResult<Vec<PendingAction>> {
        let rows = sqlx::query_as(
            "SELECT * FROM pending_actions \
             WHERE session_id = $1 AND status = 'pending' \
             ORDER BY created_at ASC",
        )
        .bind(session_id)
        .fetch_all(&self.pg)
        .await?;
        Ok(rows)
    }

    pub async fn get_stats(&self, session_id: &str) -> AppResult<PendingStats> {
        let pending: (i64,) = sqlx::query_as(
            "SELECT COUNT(*) FROM pending_actions WHERE session_id = $1 AND status = 'pending'",
        )
        .bind(session_id)
        .fetch_one(&self.pg)
        .await?;
        let failed: (i64,) = sqlx::query_as(
            "SELECT COUNT(*) FROM pending_actions WHERE session_id = $1 AND status = 'failed'",
        )
        .bind(session_id)
        .fetch_one(&self.pg)
        .await?;
        Ok(PendingStats {
            pending: pending.0,
            failed: failed.0,
        })
    }

    pub async fn sync_all(&self) -> AppResult<SyncStats> {
        if !self.oauth_apps.has_active_app().await? {
            return Ok(SyncStats {
                synced: 0,
                failed: 0,
            });
        }
        let actions: Vec<PendingAction> = sqlx::query_as(
            "SELECT * FROM pending_actions WHERE status = 'pending' \
             ORDER BY created_at ASC LIMIT 50",
        )
        .fetch_all(&self.pg)
        .await?;
        if actions.is_empty() {
            return Ok(SyncStats {
                synced: 0,
                failed: 0,
            });
        }
        self.run_actions(actions).await
    }

    pub async fn sync_for_session(&self, session_id: &str) -> AppResult<SyncStats> {
        let actions: Vec<PendingAction> = sqlx::query_as(
            "SELECT * FROM pending_actions WHERE session_id = $1 AND status = 'pending' \
             ORDER BY created_at ASC",
        )
        .bind(session_id)
        .fetch_all(&self.pg)
        .await?;
        self.run_actions(actions).await
    }

    async fn run_actions(&self, actions: Vec<PendingAction>) -> AppResult<SyncStats> {
        let mut synced = 0usize;
        let mut failed = 0usize;
        for action in actions {
            let exec = self.execute_action(&action).await;
            match exec {
                Ok(()) => {
                    sqlx::query(
                        "UPDATE pending_actions SET status = 'done', error = NULL, updated_at = now() \
                         WHERE id = $1",
                    )
                    .bind(action.id)
                    .execute(&self.pg)
                    .await?;
                    synced += 1;
                }
                Err(err) => {
                    if Self::is_ban_error(&err) {
                        warn!(
                            action_type = %action.action_type,
                            target = %action.target_urn,
                            "Still banned, skipping sync"
                        );
                        break;
                    }
                    let next_retry = action.retry_count + 1;
                    let mut error_msg = err.to_string();
                    error_msg.truncate(500);
                    if next_retry >= MAX_RETRIES {
                        sqlx::query(
                            "UPDATE pending_actions SET status = 'failed', retry_count = $1, error = $2, updated_at = now() \
                             WHERE id = $3",
                        )
                        .bind(next_retry)
                        .bind(&error_msg)
                        .bind(action.id)
                        .execute(&self.pg)
                        .await?;
                        failed += 1;
                    } else {
                        sqlx::query(
                            "UPDATE pending_actions SET retry_count = $1, error = $2, updated_at = now() \
                             WHERE id = $3",
                        )
                        .bind(next_retry)
                        .bind(&error_msg)
                        .bind(action.id)
                        .execute(&self.pg)
                        .await?;
                    }
                }
            }
        }
        Ok(SyncStats { synced, failed })
    }

    async fn execute_action(&self, action: &PendingAction) -> AppResult<()> {
        let session_id = uuid::Uuid::parse_str(&action.session_id)
            .map_err(|_| AppError::internal("invalid session_id in pending_action"))?;
        let token = self.auth.get_valid_access_token(session_id).await?;
        let urn = &action.target_urn;
        match action.action_type.as_str() {
            "like" => {
                self.sc
                    .api_post::<Value, Value>(&format!("/likes/tracks/{urn}"), &token, None)
                    .await?;
            }
            "unlike" => {
                self.sc
                    .api_delete(&format!("/likes/tracks/{urn}"), &token)
                    .await?;
            }
            "repost" => {
                self.sc
                    .api_post::<Value, Value>(&format!("/reposts/tracks/{urn}"), &token, None)
                    .await?;
            }
            "unrepost" => {
                self.sc
                    .api_delete(&format!("/reposts/tracks/{urn}"), &token)
                    .await?;
            }
            "comment" => {
                self.sc
                    .api_post_value(
                        &format!("/tracks/{urn}/comments"),
                        &token,
                        action.payload.as_ref(),
                    )
                    .await?;
            }
            "like_playlist" => {
                self.sc
                    .api_post::<Value, Value>(&format!("/likes/playlists/{urn}"), &token, None)
                    .await?;
            }
            "unlike_playlist" => {
                self.sc
                    .api_delete(&format!("/likes/playlists/{urn}"), &token)
                    .await?;
            }
            "repost_playlist" => {
                self.sc
                    .api_post::<Value, Value>(&format!("/reposts/playlists/{urn}"), &token, None)
                    .await?;
            }
            "unrepost_playlist" => {
                self.sc
                    .api_delete(&format!("/reposts/playlists/{urn}"), &token)
                    .await?;
            }
            "playlist_create" => {
                self.sc
                    .api_post_value("/playlists", &token, action.payload.as_ref())
                    .await?;
            }
            "playlist_update" => {
                self.sc
                    .api_put_value(
                        &format!("/playlists/{urn}"),
                        &token,
                        action.payload.as_ref(),
                    )
                    .await?;
            }
            "playlist_delete" => {
                self.sc
                    .api_delete(&format!("/playlists/{urn}"), &token)
                    .await?;
            }
            other => {
                warn!(action_type = other, "Unknown action type");
            }
        }
        Ok(())
    }
}
